apiVersion: v1
data:
  35.228.1.168.xip.io: ""
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    serving.knative.dev/release: devel
  name: config-domain
  namespace: knative-serving
