apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: knative-node10-runtime
spec:
  parameters:
  - name: IMAGE
    description: The URI of the image to push, including registry host
  - name: TAG
    description: Tag of the image being pushed
    default: latest
  - name: DIRECTORY
    description: The subdirectory of the workspace/repo
    default: ""
  - name: HANDLER
    default: "function.handler"
  steps:
  - name: dockerfile
    image: gcr.io/kaniko-project/executor@sha256:30ba460a034a8051b3222a32e20cb6049741e58384e3adf8c8987c004e2f2ab9
    command:
    - /busybox/sh
    args:
    - -c
    - |
      cd /workspace/${DIRECTORY}
      cat <<EOF > Dockerfile
        FROM gcr.io/triggermesh/knative-lambda-node10
        ENV _HANDLER "${HANDLER}"

        COPY . .
        RUN npm install
        ENTRYPOINT ["/opt/aws-custom-runtime"]
      EOF
  - name: export
    image: gcr.io/kaniko-project/executor@sha256:30ba460a034a8051b3222a32e20cb6049741e58384e3adf8c8987c004e2f2ab9
    args:
    - --context=/workspace/${DIRECTORY}
    - --dockerfile=/workspace/${DIRECTORY}/Dockerfile
    - --destination=${IMAGE}:${TAG}
    env:
      - name: DOCKER_CONFIG
        value: /builder/home/.docker
